server:
    port: 8081

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: h2
        password: h2
    h2:
        console:
            enabled: true
